# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Tskit Tutorials
author: Tskit Developers
# logo: logo.png

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: cache

# Information about where the book exists on the web
repository:
  url: https://github.com/tsk-dev/tutorials
  branch: main

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true

only_build_toc_files: true

sphinx:
    extra_extensions:
    - sphinx.ext.todo
    - sphinx.ext.intersphinx
    config:
      todo_include_todos: true
      intersphinx_mapping:
        tskit: ["https://tskit.readthedocs.io/en/stable", null]
        # TODO change to stable when 1.0 is released
        msprime: ["https://tskit.dev/msprime/docs/latest", null]
        pyslim: ["https://pyslim.readthedocs.io/en/stable", null]
      myst_enable_extensions:
      - colon_fence
      - deflist
